package enuns;

public enum EspecializacaoEnum {
	NEUROLOGISTA, GINECOLOGISTA, INFECTOLOGISTA, DERMATOLOGISTA, MASTOLOGISTA, CARDIOLOGISTA, OTORRINOLARINGOLOSGISTA,
	UROLOGISTA, CLINICO, PSIQUIATRA
}
